WebApiTask_2/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApiTask_2.Models;

namespace WebApiTask_2.Controllers
{
    public class CustomerController : Controller
    {
		
        // GET: Customer
        public ActionResult Index()
        {
			return View();
        }
    }
}

WebApiTask_2/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApiTask_2.Controllers
{
    public class ProductController : Controller
    {
        // GET: Product
        public ActionResult Index()
        {
            return View();
        }
    }
}

WebApiTask_2/Controllers/SaleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApiTask_2.Models;

namespace WebApiTask_2.Controllers
{
    public class SaleController : Controller
    {
		StoreDbContext db = new StoreDbContext();
        // GET: Sale
        public ActionResult Index()
        {
			//List<Customer> saleCust = db.Customers.ToList();

            return View();
        }
    }
}

WebApiTask_2/Controllers/StoreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApiTask_2.Controllers
{
    public class StoreController : Controller
    {
        // GET: Store
        public ActionResult Index()
        {
            return View();
        }
    }
}

WebApiTask_2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Keys - OnBoarding", "Index", "Customer", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
				<ul class="nav navbar-nav">
					<li>@Html.ActionLink("Customers", "Index", "Customer", new { area = "" }, null)</li>
					<li>@Html.ActionLink("Products", "Index", "Product", new { area = "" }, null)</li>
					<li>@Html.ActionLink("Stores", "Index", "Store", new { area = "" }, null)</li>
					<li>@Html.ActionLink("Sales", "Index", "Sale", new { area = "" }, null)</li>
				</ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>